[System]
Test_In_CHMB1 = True
Test_In_CHMB2 = False
MSA_Number_Of_Repeats = 50
[MID]
System_Supplier_ECU_Software_Number = "SinglPepsHw001"
System_Supplier_ECU_Software_Version = "12.08.01"
Bootloader_Sofware_Number  = "STLAs_EPSAFBL"
Bootloader_Software_Version = "01 01 00"
Calibration_0_Realese_Information = "36061"
Calibration_1_Realese_Information = ""
Calibration_2_Realese_Information = ""
HW_Part_Number = "28316489"
HW_Part_Revision = "009"
XCP_T1_Address = "0x60,0xC3,0xBE,0xFE"
XCP_T2_Address = "0x64,0xC3,0xBE,0xFE"
XCP_Motor_Speed_Address = "0xE0,0xC3,0xBE,0xFE"
XCP_Temperature_Address = "0x0C,0xC5,0xBE,0xFE"
XCP_Battery_Voltage_Address = "0x20,0xC4,0xBE,0xFE"
XCP_Motor_Current_Address = "0xA8,0xC3,0xBE,0xFE"
Polarity = "0x01,0x18,0x10,0x00"
## Order from XCP addresses is inversed byte by byte-> from febec50c->fe|be|c5|0c -> please input"0x0C,0xC5,0xBE,0xFE"
[HI_RHD]
System_Supplier_ECU_Software_Number = "DualPepsHw001B"
System_Supplier_ECU_Software_Version = "12.08.02"
Bootloader_Sofware_Number  = "STLAs_EPSAFBL"
Bootloader_Software_Version = "01 01 00"
Calibration_0_Realese_Information = "36062"
Calibration_1_Realese_Information = ""
Calibration_2_Realese_Information = ""
HW_Part_Number = "28316489"
HW_Part_Revision = "009"
XCP_T1_Address = "0x60,0xC3,0xBE,0xFE"
XCP_T2_Address = "0x64,0xC3,0xBE,0xFE"
XCP_Motor_Speed_Address = "0xE0,0xC3,0xBE,0xFE"
XCP_Temperature_Address = "0x0C,0xC5,0xBE,0xFE"
XCP_Battery_Voltage_Address = "0x20,0xC4,0xBE,0xFE"
XCP_Motor_Current_Address = "0xA8,0xC3,0xBE,0xFE"
Polarity = "0x01,0x18,0x10,0x00"
[HI_LHD]
System_Supplier_ECU_Software_Number = "DualPepsHw001B"
System_Supplier_ECU_Software_Version = "12.08.02"
Bootloader_Sofware_Number  = "STLAs_EPSAFBL"
Bootloader_Software_Version = "01 01 00"
Calibration_0_Realese_Information = "36062"
Calibration_1_Realese_Information = ""
Calibration_2_Realese_Information = ""
HW_Part_Number = "28316489"
HW_Part_Revision = "009"
XCP_T1_Address = "0x60,0xC3,0xBE,0xFE"
XCP_T2_Address = "0x64,0xC3,0xBE,0xFE"
XCP_Motor_Speed_Address = "0xE0,0xC3,0xBE,0xFE"
XCP_Temperature_Address = "0x0C,0xC5,0xBE,0xFE"
XCP_Battery_Voltage_Address = "0x20,0xC4,0xBE,0xFE"
XCP_Motor_Current_Address = "0xA8,0xC3,0xBE,0xFE"
Polarity = "0x01,0x18,0x10,0x00"