[System]
Numato1_Name = Relay_Board_DUT1
Numato1_Port= COM8
Numato2_Name = Relay_Board_DUT2
Numato2_Port = COM9
PCIe_DIO_card = 
PCI_DO_card = 
TDK_20_38_DUT1 = 
TDK_20_38_DUT2 = 
TDK_20_38_DUT3 = 
TDK_20_38_DUT4 = 
TDK_20_50_DUT1 = 
TDK_20_50_DUT2 = 
TDK_20_50_DUT3 = 
TDK_20_50_DUT4 = 
DMM_Address = 192.168.100.10
DMM_Name = DMM
Rigol1_Address = 192.168.100.11
Rigol1_Name = Rigol1
Scanner_DUT1 = "COM17"
Scanner_DUT2 = "COM18"
Scanner_DUT3 = "COM19"
Scanner_DUT4 = "COM20"
PEAK_CAN_DUT1 = 
PEAK_CAN_DUT2 = 
PEAK_CAN_DUT3 = 
PEAK_CAN_DUT4 = 
[Cassete_Coding]
Variant1 = 01
Varaint2 = 10
## the relay numbers start from 0
[Numato_Relays_CHMB1_DUT1]
DMM_LO_BAT-_DUT1 = 0
DMM_HI_BAT+_DUT1 = 1
DMM_HI_VS5N_DUT1 = 2
DMM_HI_CANL_DUT1 = 3
DMM_HI_CANH_DUT1 = 4
DMM_I_BAT-_DUT1 = 5
CANL_DUT1 = 6
CANH_DUT1 = 7
CAL_PS+_DUT1 = 8
CAL_PS-_DUT1 = 9
Resistor__Capacitor_Discharge_DUT1 = 10
Sense+_DUT1 = 11
Sense-_DUT1 = 12
Fan_DUT1 = 30
[Numato_Relays_CHMB1_DUT2]
DMM_LO_BAT-_DUT2 = 17
DMM_HI_BAT+_DUT2 = 18
DMM_HI_VS5N_DUT2 = 19
DMM_HI_CANL_DUT2 = 20
DMM_HI_CANH_DUT2 = 21
DMM_I_BAT-_DUT2 = 22
CANL_DUT2 = 23
CANH_DUT2 = 24
CAL_PS+_DUT2 = 25
CAL_PS-_DUT2 = 26
Resistor__Capacitor_Discharge_DUT2 = 27
Sense+_DUT2 = 28
Sense-_DUT2 = 29
Fan_DUT2 = 31
[Numato_Relays_CHMB1]
Magnetic_CW_1_CHMB1 = 13
Magnetic_CCW_1_CHMB1 = 14
Magnetic_CW_2_CHMB1 = 15
Magnetic_CCW_2_CHMB1 = 16
[Numato_Relays_CHMB2_DUT1]
DMM_LO_BAT-_DUT3 = 0
DMM_HI_BAT+_DUT3 = 1
DMM_HI_VS5N_DUT3 = 2
DMM_HI_CANL_DUT3 = 3
DMM_HI_CANH_DUT3 = 4
DMM_I_BAT-_DUT3 = 5
CANL_DUT3 = 6
CANH_DUT3 = 7
CAL_PS+_DUT3 = 8
CAL_PS-_DUT3 = 9
Resistor__Capacitor_Discharge_DUT3 = 10
Sense+_DUT3 = 11
Sense-_DUT3 = 12
Fan_DUT3 = 30
[Numato_Relays_CHMB2_DUT2]
DMM_LO_BAT-_DUT4 = 17
DMM_HI_BAT+_DUT4 = 18
DMM_HI_VS5N_DUT4 = 19
DMM_HI_CANL_DUT4 = 20
DMM_HI_CANH_DUT4 = 21
DMM_I_BAT-_DUT4 = 22
CANL_DUT4 = 23
CANH_DUT4 = 24
CAL_PS+_DUT4 = 25
CAL_PS-_DUT4 = 26
Resistor__Capacitor_Discharge_DUT4 = 27
Sense+_DUT4 = 28
Sense-_DUT4 = 29
Fan_DUT4 = 31
[Numato_Relays_CHMB2]
Magnetic_CW_1_CHMB3 = 13
Magnetic_CCW_1_CHMB3 = 14
Magnetic_CW_2_CHMB3 = 15
Magnetic_CCW_2_CHMB3 = 16
##DI ports are separated to port 0 and port1. The values are from 1 but in VI are loaded as -1
## they are loaded like that to start from 0 value as the bits do
[DI_Card0_Port0]
Cassette_Code_Byte0 = 1
Cassette_Code_Byte1 = 2
DUT_Present_DUT1 = 3
DUT_Present_DUT2 = 4
DUT_Present_DUT3 = 5
DUT_Present_DUT4 = 6
Fixture_Closed_CHMB1 = 7
Fixture_Closed_CHMB2 = 8
[DI_Card0_Port1]
NOK_Button_CHMB1 = 1
NOK_Button_CHMB2 = 2
Emergency_STOP = 3
Motor_Ready_Running_DUT1 = 4
Motor_Ready_Running_DUT2 = 5
Motor_Ready_Running_DUT3 = 6
Motor_Ready_Running_DUT4 = 7
Spare = 8
##Currently there is only port 0 for DO. The COM1 is not wired, so keep it in mind if number of added
## outputs exceed these 8 that are available
## here are values from 1 but they are saved from 0
##DO Card0 Ports 0 and 1 are set in teststand, here is for informational purposes
[DO_Card0_Port0] 
Motor_Enable_DUT1 = 1
Motor_Target_Bit0_DUT1 = 2
Motor_Target_Bit1_DUT1 = 3
Motor_Enable_DUT2 = 4
Motor_Target_Bit0_DUT2 = 5
Motor_Target_Bit1_DUT2 = 6
Tower_Lamp_RD = 7
Tower_Lamp_YE = 8
##DO Card0 Ports 0 and 1 are set in teststand, here is for informational purposes
[DO_Card0_Port1]
Motor_Enable_DUT3 = 1
Motor_Target_Bit0_DUT3 = 2
Motor_Target_Bit1_DUT3 = 3
Motor_Enable_DUT4 = 4
Motor_Target_Bit0_DUT4 = 5
Motor_Target_Bit1_DUT4 = 6
Tower_Lamp_GN = 7
Reset_Button_Lamp = 8
##Next sets of signals are loaded directly in test steps based on test socket
[DO_Card1_Port0]
High_Current_Relay_Plus_DUT1 = 1
High_Current_Relay_Minus_DUT1 = 2
High_Current_Relay_Plus_DUT2 = 3
High_Current_Relay_Minus_DUT2 = 4
High_Current_Relay_Plus_DUT3 = 5
High_Current_Relay_Minus_DUT3 = 6
High_Current_Relay_Plus_DUT4 = 7
High_Current_Relay_Minus_DUT4 = 8
##Next sets of signals are loaded directly in test steps based on test socket
[DO_Card1_Port1]
Load_Phase_A_B_C_DUT1 = 1
Load_Phase_D_E_F_DUT1 = 2
Load_Phase_A_B_C_DUT2 = 3
Load_Phase_D_E_F_DUT2 = 4
Load_Phase_A_B_C_DUT3 = 5
Load_Phase_D_E_F_DUT3 = 6
Load_Phase_A_B_C_DUT4 = 7
Load_Phase_D_E_F_DUT4 = 8
##Next sets of signals are loaded directly in test steps based on test socket
[DO_Card1_Port2]
Load_Calibration_A_B_C_DUT1 = 1
Load_Calibration_D_E_F_DUT1 = 2
Load_Calibration_A_B_C_DUT2 = 3
Load_Calibration_D_E_F_DUT2 = 4
Load_Calibration_A_B_C_DUT3 = 5
Load_Calibration_D_E_F_DUT3 = 6
Load_Calibration_A_B_C_DUT4 = 7
Load_Calibration_D_E_F_DUT4 = 8
##DO Card1 Ports 3 is set in teststand, here is for informational purposes (DMM in test steps and Lock in Station interface)
[DO_Card1_Port3]
DMM_LO_PS_minus_DUT1 = 1
DMM_LO_PS_minus_DUT2 = 2
DMM_LO_PS_minus_DUT3 = 3
DMM_LO_PS_minus_DUT4 = 4
Fixture_Lock_CHMB1 = 5
Fixture_Lock_CHMB2 = 6
Spare1 = 7
Spare2 = 8